### ISSUE TITLE
Latest version on crates.io

### ISSUE THREAD

**Issue by orhun** [TheNeikos/textwidth-rs#3]
Hi,
Is this crate going to be updated on [crates.io](https://crates.io/crates/textwidth)? Right now I'm using `textwidth` like the following:

```
textwidth = { git = "https://github.com/TheNeikos/textwidth-rs", version = "1.2.0"}
```
That'd be great to use the latest version from [crates.io](https://crates.io/crates/textwidth)

Thanks,
orhun.

**Comment by TheNeikos** [comment]
Heya!

So I published the new version, you can find it here: https://crates.io/crates/textwidth

I had to bump the version to 2.0, as changing the Error type like that is a breaking change. It is much better like this though, so thank you laying out the groundwork!

**Comment by orhun** [comment]
Awesome 🥂
